import json
import re

with open("c:/Users/kravor-x/Downloads/atlantic/src/assets/languages/tr.json", "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    "Bəli": "Evet",
    "Xeyr": "Hayır",
    "Əlavə et": "Ekle",
    "Yüklənir...": "Yükleniyor...",
    "Naməlum": "Bilinmeyen",
    "Haqqında": "Hakkında",
    "haqqında": "hakkında",
    "və": "ve",
    "Tətbiq": "Uygulama",
    "Quraşdırma": "Kurulum",
    "Parametrlər": "Ayarlar",
    "parametrlər": "ayarlar",
    "Dil": "Dil",
    "Seç": "Seç",
    "Bütün": "Tüm",
    "İstifadəçi": "Kullanıcı",
    "istifadəçi": "kullanıcı",
    "Şəbəkə": "Ağ",
    "şəbəkə": "ağ",
    "Səs": "Ses",
    "səs": "ses",
    "Cihaz": "Cihaz",
    "cihaz": "cihaz",
    "Qoşulub": "Bağlandı",
    "Qoşulur": "Bağlanıyor",
    "Bağlıdır": "Bağlı",
    "Açıq": "Açık",
    "İmtina": "İptal",
    "Ləğv et": "İptal et",
    "Saxla": "Kaydet",
    "Geri": "Geri",
    "İrəli": "İleri",
    "Təstiqlə": "Onayla",
    "Məlumat": "Bilgi",
    "Sil": "Sil",
    "Yenilə": "Güncelle",
    "Axtar": "Ara",
    "Sistem": "Sistem",
    "Fayl": "Dosya",
    "Qovluq": "Klasör",
    "Burax": "Bırak",
    "Oxu": "Oku",
    "Yaz": "Yaz",
    "Çıxış": "Çıkış",
    "Daxil ol": "Giriş yap",
    "Şifrə": "Şifre",
    "Ad": "Ad",
    "Soyad": "Soyad",
    "Ekran": "Ekran",
    "Görünüş": "Görünüm",
    "Mövzu": "Tema",
    "Arxa plan": "Arka plan",
    "Şəkil": "Resim",
    "Parlaqlıq": "Parlaklık",
    "Səviyyə": "Seviye",
    "Azərbaycanca": "Türkçe",
    "azerbaycanca": "türkçe",
    "Yenilənmə": "Güncelleme",
    "Mövcuddur": "Mevcut",
    "Xəta": "Hata",
    "Uğurlu": "Başarılı",
    "Uğursuz": "Başarısız",
    "Başla": "Başla",
    "Dayandır": "Durdur",
    "Davam et": "Devam et",
    "Sonlandır": "Sonlandır",
    "Əsas": "Ana",
    "Digər": "Diğer",
    "Həcm": "Hacim",
    "Ölçü": "Boyut",
    "Rəng": "Renk",
    "Şrift": "Yazı Tipi",
    "Ümumi": "Genel",
    "Ətraflı": "Detaylı",
    "Dəyişdir": "Değiştir",
    "Nizamlamalar": "Ayarlar",
    "Rejim": "Mod",
    "Tənzimləmələr": "Ayarlar",
    "Səs səviyyəsi": "Ses seviyesi",
    "Seçimlər": "Seçenekler",
    "Dəyişikliklər": "Değişiklikler",
    "Nəticə": "Sonuç",
    "Zaman": "Zaman",
    "Saat": "Saat",
    "Gün": "Gün",
    "Həftə": "Hafta",
    "Ay": "Ay",
    "İl": "Yıl",
    "Göstər": "Göster",
    "Gizlət": "Gizle",
    "Aktiv": "Aktif",
    "Deaktiv": "Pasif",
    "Aktivləşdir": "Etkinleştir",
    "Deaktivləşdir": "Devre dışı bırak"
}

for az_word, tr_word in replacements.items():
    content = content.replace(az_word, tr_word)

with open("c:/Users/kravor-x/Downloads/atlantic/src/assets/languages/tr.json", "w", encoding="utf-8") as f:
    f.write(content)
print("Done")
